# Generated by Django 4.0.3 on 2022-05-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
