# Generated by Django 4.0.3 on 2022-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_type',
            field=models.CharField(choices=[('asin_search', 'ASIN Search')], default='asin_search', max_length=500),
            preserve_default=False,
        ),
    ]
