# Generated by Django 4.0.3 on 2022-06-03 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_history_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('asin', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('reviews', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.CharField(blank=True, max_length=500, null=True)),
                ('listing_date', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.CharField(blank=True, max_length=500, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=500, null=True)),
                ('seasonality', models.CharField(blank=True, max_length=500, null=True)),
                ('attr', models.CharField(blank=True, max_length=10000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterField(
            model_name='history',
            name='history_type',
            field=models.CharField(choices=[('asin_search', 'ASIN Search'), ('recommendation', 'Recommendation')], max_length=500),
        ),
    ]
