# Generated by Django 4.0.3 on 2022-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_alter_history_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attr',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
