# Generated by Django 4.0.3 on 2022-06-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_criteria_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='country',
        ),
    ]
