# Generated by Django 4.0.3 on 2022-06-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_category_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='421d2cfe-c0f2-4cda-9842-09d424f9a6c9', on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
            preserve_default=False,
        ),
    ]
